name: "Meross Local Broker Addon"
version: "0.0.1-alpha01"
description: "Enables LAN-ONLY broker, avoiding Meross Cloud usage."
slug: "meross_local_broker"
image: "ghcr.io/albertogeniola/{arch}-meross_local_broker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  2001/tcp: 2001
  2002/tcp: 2002
  10001/tcp: 10001
ports_description:
  2001/tcp: "MQTT Broker port"
  2002/tcp: "HTTP API port"
  10001/tcp: "Remote debugger port"
ingress: true
#ingress_port: 8099
ingress_port: 0
host_network: true
homeassistant: "1.0.0"
options:
  resetdb: False
schema:
  resetdb: "bool"
environment:
  debug: false
  debug_port: 10001
