name: "Meross Local Broker Addon"
version: "0.0.1-alpha25"
description: "Enables LAN-ONLY broker, avoiding Meross Cloud usage."
slug: "meross_local_broker"
image: "ghcr.io/albertogeniola/{arch}-meross_local_broker"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  2001/tcp: 2001
  2002/tcp: 2002
  10001/tcp: 10001
ports_description:
  2001/tcp: "MQTT Broker port"
  2002/tcp: "HTTP API port"
  10001/tcp: "Remote debugger port"
ingress: true
startup: services
panel_icon: mdi-power-socket-us
panel_title: Meross Addon
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
ingress_port: 8099
#ingress_port: 0
#host_network: true
host_dbus: true
homeassistant: "1.0.0"
options:
  reinit_db: false
  advertise: true
  debug_mode: false
  debug_port: 10001
schema:
  reinit_db: "bool"
  advertise: "bool"
  debug_mode: "bool"
  debug_port: "int"
